package com.connect.quant.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ACCOUNT
 *
 * @mbg.generated do_not_delete_during_merge Tue Aug 07 14:58:26 CST 2018
 */
public class Account {
	private Integer sno;
	/** 账户代码 */
	private String accountId;
	/** 账户在vt中的唯一代码，通常是 Gateway名.账户代码 */
	private String vtAccountId;
	/** 昨日账户结算净值 */
	private double preBalance;
	/** 账户净值 */
	private double balance;
	/** 可用资金 */
	private double available;
	/** 今日手续费 */
	private double commission;
	/** 保证金占用 */
	private double margin;
	/** 平仓盈亏 */
	private double closeProfit;
	/** 持仓盈亏 */
	private double positionProfit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.SNO
     *
     * @return the value of ACCOUNT.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.SNO
     *
     * @param sno the value for ACCOUNT.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCOUNT_ID
     *
     * @return the value of ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCOUNT_ID
     *
     * @param accountId the value for ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.VT_ACCOUNT_ID
     *
     * @return the value of ACCOUNT.VT_ACCOUNT_ID
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getVtAccountId() {
        return vtAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.VT_ACCOUNT_ID
     *
     * @param vtAccountId the value for ACCOUNT.VT_ACCOUNT_ID
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setVtAccountId(String vtAccountId) {
        this.vtAccountId = vtAccountId == null ? null : vtAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PRE_BALANCE
     *
     * @return the value of ACCOUNT.PRE_BALANCE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPreBalance() {
        return preBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PRE_BALANCE
     *
     * @param preBalance the value for ACCOUNT.PRE_BALANCE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPreBalance(Double preBalance) {
        this.preBalance = preBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.BALANCE
     *
     * @return the value of ACCOUNT.BALANCE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.BALANCE
     *
     * @param balance the value for ACCOUNT.BALANCE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.AVAILABLE
     *
     * @return the value of ACCOUNT.AVAILABLE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.AVAILABLE
     *
     * @param available the value for ACCOUNT.AVAILABLE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAvailable(Double available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.COMMISSION
     *
     * @return the value of ACCOUNT.COMMISSION
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.COMMISSION
     *
     * @param commission the value for ACCOUNT.COMMISSION
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCommission(Double commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.MARGIN
     *
     * @return the value of ACCOUNT.MARGIN
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.MARGIN
     *
     * @param margin the value for ACCOUNT.MARGIN
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setMargin(Double margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.CLOSE_PROFIT
     *
     * @return the value of ACCOUNT.CLOSE_PROFIT
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCloseProfit() {
        return closeProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.CLOSE_PROFIT
     *
     * @param closeProfit the value for ACCOUNT.CLOSE_PROFIT
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCloseProfit(Double closeProfit) {
        this.closeProfit = closeProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.POSITION_PROFIT
     *
     * @return the value of ACCOUNT.POSITION_PROFIT
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPositionProfit() {
        return positionProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.POSITION_PROFIT
     *
     * @param positionProfit the value for ACCOUNT.POSITION_PROFIT
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPositionProfit(Double positionProfit) {
        this.positionProfit = positionProfit;
    }
}