package com.connect.quant.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table FUTURE_QUOTE
 *
 * @mbg.generated do_not_delete_during_merge Fri Aug 03 11:21:49 CST 2018
 */
public class FutureQuote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.SNO
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Integer sno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.NAME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.OPENINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double openingprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.CLOSINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double closingprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.CURRENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double currentprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.HIGHESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double highestprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.LOWESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double lowestprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.COMPETITIVEBUYPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double competitivebuyprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.COMPETITIVESALEPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double competitivesaleprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.NUMBEROFHELD
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long numberofheld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.NUMBEROFTRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long numberoftraded;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.AMOUNTOFBUY
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofbuy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.AMOUNTOFSALE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofsale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.PRICEOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.DATE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.TIME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.ID
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.SETTLEMENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double settlementprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.LASTSETTLEMENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double lastsettlementprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.MARKET
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private String market;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUTURE_QUOTE.CATEGORY
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private String category;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.SNO
	 * @return  the value of FUTURE_QUOTE.SNO
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Integer getSno() {
		return sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.SNO
	 * @param sno  the value for FUTURE_QUOTE.SNO
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setSno(Integer sno) {
		this.sno = sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.NAME
	 * @return  the value of FUTURE_QUOTE.NAME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.NAME
	 * @param name  the value for FUTURE_QUOTE.NAME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.OPENINGPRICE
	 * @return  the value of FUTURE_QUOTE.OPENINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getOpeningprice() {
		return openingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.OPENINGPRICE
	 * @param openingprice  the value for FUTURE_QUOTE.OPENINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setOpeningprice(Double openingprice) {
		this.openingprice = openingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.CLOSINGPRICE
	 * @return  the value of FUTURE_QUOTE.CLOSINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getClosingprice() {
		return closingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.CLOSINGPRICE
	 * @param closingprice  the value for FUTURE_QUOTE.CLOSINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setClosingprice(Double closingprice) {
		this.closingprice = closingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.CURRENTPRICE
	 * @return  the value of FUTURE_QUOTE.CURRENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getCurrentprice() {
		return currentprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.CURRENTPRICE
	 * @param currentprice  the value for FUTURE_QUOTE.CURRENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCurrentprice(Double currentprice) {
		this.currentprice = currentprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.HIGHESTPRICE
	 * @return  the value of FUTURE_QUOTE.HIGHESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getHighestprice() {
		return highestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.HIGHESTPRICE
	 * @param highestprice  the value for FUTURE_QUOTE.HIGHESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setHighestprice(Double highestprice) {
		this.highestprice = highestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.LOWESTPRICE
	 * @return  the value of FUTURE_QUOTE.LOWESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getLowestprice() {
		return lowestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.LOWESTPRICE
	 * @param lowestprice  the value for FUTURE_QUOTE.LOWESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setLowestprice(Double lowestprice) {
		this.lowestprice = lowestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.COMPETITIVEBUYPRICE
	 * @return  the value of FUTURE_QUOTE.COMPETITIVEBUYPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getCompetitivebuyprice() {
		return competitivebuyprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.COMPETITIVEBUYPRICE
	 * @param competitivebuyprice  the value for FUTURE_QUOTE.COMPETITIVEBUYPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCompetitivebuyprice(Double competitivebuyprice) {
		this.competitivebuyprice = competitivebuyprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.COMPETITIVESALEPRICE
	 * @return  the value of FUTURE_QUOTE.COMPETITIVESALEPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getCompetitivesaleprice() {
		return competitivesaleprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.COMPETITIVESALEPRICE
	 * @param competitivesaleprice  the value for FUTURE_QUOTE.COMPETITIVESALEPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCompetitivesaleprice(Double competitivesaleprice) {
		this.competitivesaleprice = competitivesaleprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.NUMBEROFHELD
	 * @return  the value of FUTURE_QUOTE.NUMBEROFHELD
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getNumberofheld() {
		return numberofheld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.NUMBEROFHELD
	 * @param numberofheld  the value for FUTURE_QUOTE.NUMBEROFHELD
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setNumberofheld(Long numberofheld) {
		this.numberofheld = numberofheld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.NUMBEROFTRADED
	 * @return  the value of FUTURE_QUOTE.NUMBEROFTRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getNumberoftraded() {
		return numberoftraded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.NUMBEROFTRADED
	 * @param numberoftraded  the value for FUTURE_QUOTE.NUMBEROFTRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setNumberoftraded(Long numberoftraded) {
		this.numberoftraded = numberoftraded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.AMOUNTOFBUY
	 * @return  the value of FUTURE_QUOTE.AMOUNTOFBUY
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofbuy() {
		return amountofbuy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.AMOUNTOFBUY
	 * @param amountofbuy  the value for FUTURE_QUOTE.AMOUNTOFBUY
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofbuy(Long amountofbuy) {
		this.amountofbuy = amountofbuy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFBUY1
	 * @return  the value of FUTURE_QUOTE.PRICEOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy1() {
		return priceofbuy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFBUY1
	 * @param priceofbuy1  the value for FUTURE_QUOTE.PRICEOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy1(Double priceofbuy1) {
		this.priceofbuy1 = priceofbuy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFBUY2
	 * @return  the value of FUTURE_QUOTE.PRICEOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy2() {
		return priceofbuy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFBUY2
	 * @param priceofbuy2  the value for FUTURE_QUOTE.PRICEOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy2(Double priceofbuy2) {
		this.priceofbuy2 = priceofbuy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFBUY3
	 * @return  the value of FUTURE_QUOTE.PRICEOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy3() {
		return priceofbuy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFBUY3
	 * @param priceofbuy3  the value for FUTURE_QUOTE.PRICEOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy3(Double priceofbuy3) {
		this.priceofbuy3 = priceofbuy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFBUY4
	 * @return  the value of FUTURE_QUOTE.PRICEOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy4() {
		return priceofbuy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFBUY4
	 * @param priceofbuy4  the value for FUTURE_QUOTE.PRICEOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy4(Double priceofbuy4) {
		this.priceofbuy4 = priceofbuy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFBUY5
	 * @return  the value of FUTURE_QUOTE.PRICEOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy5() {
		return priceofbuy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFBUY5
	 * @param priceofbuy5  the value for FUTURE_QUOTE.PRICEOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy5(Double priceofbuy5) {
		this.priceofbuy5 = priceofbuy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.AMOUNTOFSALE
	 * @return  the value of FUTURE_QUOTE.AMOUNTOFSALE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofsale() {
		return amountofsale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.AMOUNTOFSALE
	 * @param amountofsale  the value for FUTURE_QUOTE.AMOUNTOFSALE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofsale(Long amountofsale) {
		this.amountofsale = amountofsale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFSALE1
	 * @return  the value of FUTURE_QUOTE.PRICEOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale1() {
		return priceofsale1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFSALE1
	 * @param priceofsale1  the value for FUTURE_QUOTE.PRICEOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale1(Double priceofsale1) {
		this.priceofsale1 = priceofsale1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFSALE2
	 * @return  the value of FUTURE_QUOTE.PRICEOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale2() {
		return priceofsale2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFSALE2
	 * @param priceofsale2  the value for FUTURE_QUOTE.PRICEOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale2(Double priceofsale2) {
		this.priceofsale2 = priceofsale2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFSALE3
	 * @return  the value of FUTURE_QUOTE.PRICEOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale3() {
		return priceofsale3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFSALE3
	 * @param priceofsale3  the value for FUTURE_QUOTE.PRICEOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale3(Double priceofsale3) {
		this.priceofsale3 = priceofsale3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFSALE4
	 * @return  the value of FUTURE_QUOTE.PRICEOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale4() {
		return priceofsale4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFSALE4
	 * @param priceofsale4  the value for FUTURE_QUOTE.PRICEOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale4(Double priceofsale4) {
		this.priceofsale4 = priceofsale4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.PRICEOFSALE5
	 * @return  the value of FUTURE_QUOTE.PRICEOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale5() {
		return priceofsale5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.PRICEOFSALE5
	 * @param priceofsale5  the value for FUTURE_QUOTE.PRICEOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale5(Double priceofsale5) {
		this.priceofsale5 = priceofsale5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.DATE
	 * @return  the value of FUTURE_QUOTE.DATE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.DATE
	 * @param date  the value for FUTURE_QUOTE.DATE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.TIME
	 * @return  the value of FUTURE_QUOTE.TIME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.TIME
	 * @param time  the value for FUTURE_QUOTE.TIME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.ID
	 * @return  the value of FUTURE_QUOTE.ID
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.ID
	 * @param id  the value for FUTURE_QUOTE.ID
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.SETTLEMENTPRICE
	 * @return  the value of FUTURE_QUOTE.SETTLEMENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getSettlementprice() {
		return settlementprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.SETTLEMENTPRICE
	 * @param settlementprice  the value for FUTURE_QUOTE.SETTLEMENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setSettlementprice(Double settlementprice) {
		this.settlementprice = settlementprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.LASTSETTLEMENTPRICE
	 * @return  the value of FUTURE_QUOTE.LASTSETTLEMENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getLastsettlementprice() {
		return lastsettlementprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.LASTSETTLEMENTPRICE
	 * @param lastsettlementprice  the value for FUTURE_QUOTE.LASTSETTLEMENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setLastsettlementprice(Double lastsettlementprice) {
		this.lastsettlementprice = lastsettlementprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.MARKET
	 * @return  the value of FUTURE_QUOTE.MARKET
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public String getMarket() {
		return market;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.MARKET
	 * @param market  the value for FUTURE_QUOTE.MARKET
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setMarket(String market) {
		this.market = market == null ? null : market.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUTURE_QUOTE.CATEGORY
	 * @return  the value of FUTURE_QUOTE.CATEGORY
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUTURE_QUOTE.CATEGORY
	 * @param category  the value for FUTURE_QUOTE.CATEGORY
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCategory(String category) {
		this.category = category == null ? null : category.trim();
	}
}