package com.connect.quant.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table POSITIONS
 *
 * @mbg.generated do_not_delete_during_merge Thu Aug 30 13:02:13 CST 2018
 */
public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.SNO
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.SYMBOL
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.EXCHANGE
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.VT_SYMBOL
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private String vtSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.DIRECTION
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.POSITIONS
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private Integer positions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.FROZEN
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private Integer frozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.PRICE
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.VT_POSITION_NAME
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private String vtPositionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.YD_POSITION
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private Integer ydPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.POSITION_PROFIT
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private Double positionProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITIONS.ACCOUNT_ID
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    private String accountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.SNO
     *
     * @return the value of POSITIONS.SNO
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.SNO
     *
     * @param sno the value for POSITIONS.SNO
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.SYMBOL
     *
     * @return the value of POSITIONS.SYMBOL
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.SYMBOL
     *
     * @param symbol the value for POSITIONS.SYMBOL
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.EXCHANGE
     *
     * @return the value of POSITIONS.EXCHANGE
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.EXCHANGE
     *
     * @param exchange the value for POSITIONS.EXCHANGE
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.VT_SYMBOL
     *
     * @return the value of POSITIONS.VT_SYMBOL
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public String getVtSymbol() {
        return vtSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.VT_SYMBOL
     *
     * @param vtSymbol the value for POSITIONS.VT_SYMBOL
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setVtSymbol(String vtSymbol) {
        this.vtSymbol = vtSymbol == null ? null : vtSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.DIRECTION
     *
     * @return the value of POSITIONS.DIRECTION
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.DIRECTION
     *
     * @param direction the value for POSITIONS.DIRECTION
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.POSITIONS
     *
     * @return the value of POSITIONS.POSITIONS
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public Integer getPositions() {
        return positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.POSITIONS
     *
     * @param positions the value for POSITIONS.POSITIONS
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setPositions(Integer positions) {
        this.positions = positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.FROZEN
     *
     * @return the value of POSITIONS.FROZEN
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public Integer getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.FROZEN
     *
     * @param frozen the value for POSITIONS.FROZEN
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setFrozen(Integer frozen) {
        this.frozen = frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.PRICE
     *
     * @return the value of POSITIONS.PRICE
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.PRICE
     *
     * @param price the value for POSITIONS.PRICE
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.VT_POSITION_NAME
     *
     * @return the value of POSITIONS.VT_POSITION_NAME
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public String getVtPositionName() {
        return vtPositionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.VT_POSITION_NAME
     *
     * @param vtPositionName the value for POSITIONS.VT_POSITION_NAME
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setVtPositionName(String vtPositionName) {
        this.vtPositionName = vtPositionName == null ? null : vtPositionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.YD_POSITION
     *
     * @return the value of POSITIONS.YD_POSITION
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public Integer getYdPosition() {
        return ydPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.YD_POSITION
     *
     * @param ydPosition the value for POSITIONS.YD_POSITION
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setYdPosition(Integer ydPosition) {
        this.ydPosition = ydPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.POSITION_PROFIT
     *
     * @return the value of POSITIONS.POSITION_PROFIT
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public Double getPositionProfit() {
        return positionProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.POSITION_PROFIT
     *
     * @param positionProfit the value for POSITIONS.POSITION_PROFIT
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setPositionProfit(Double positionProfit) {
        this.positionProfit = positionProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITIONS.ACCOUNT_ID
     *
     * @return the value of POSITIONS.ACCOUNT_ID
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITIONS.ACCOUNT_ID
     *
     * @param accountId the value for POSITIONS.ACCOUNT_ID
     *
     * @mbg.generated Thu Aug 30 13:02:13 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }
}