package com.connect.quant.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PRODUCT_QUOTE
 *
 * @mbg.generated do_not_delete_during_merge Tue Aug 07 14:58:26 CST 2018
 */
public class ProductQuote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.NAME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.OPENING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double openingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.CLOSING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double closingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.CURRENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double currentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.HIGHEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double highestPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.LOWEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double lowestPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double competitiveBuyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double competitiveSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.NUMBER_OF_HELD
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long numberOfHeld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.NUMBER_OF_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long numberOfTraded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.AMOUNT_OF_BUY
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfBuy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.AMOUNT_OF_SALE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.PRICE_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.DATE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.TIME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.SYMBOL
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.SETTLEMENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double settlementPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.LAST_SETTLEMENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double lastSettlementPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.EXCHANGE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_QUOTE.CATEGORY
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.SNO
     *
     * @return the value of PRODUCT_QUOTE.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.SNO
     *
     * @param sno the value for PRODUCT_QUOTE.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.NAME
     *
     * @return the value of PRODUCT_QUOTE.NAME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.NAME
     *
     * @param name the value for PRODUCT_QUOTE.NAME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.OPENING_PRICE
     *
     * @return the value of PRODUCT_QUOTE.OPENING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getOpeningPrice() {
        return openingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.OPENING_PRICE
     *
     * @param openingPrice the value for PRODUCT_QUOTE.OPENING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setOpeningPrice(Double openingPrice) {
        this.openingPrice = openingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.CLOSING_PRICE
     *
     * @return the value of PRODUCT_QUOTE.CLOSING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getClosingPrice() {
        return closingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.CLOSING_PRICE
     *
     * @param closingPrice the value for PRODUCT_QUOTE.CLOSING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setClosingPrice(Double closingPrice) {
        this.closingPrice = closingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.CURRENT_PRICE
     *
     * @return the value of PRODUCT_QUOTE.CURRENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.CURRENT_PRICE
     *
     * @param currentPrice the value for PRODUCT_QUOTE.CURRENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.HIGHEST_PRICE
     *
     * @return the value of PRODUCT_QUOTE.HIGHEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getHighestPrice() {
        return highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.HIGHEST_PRICE
     *
     * @param highestPrice the value for PRODUCT_QUOTE.HIGHEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setHighestPrice(Double highestPrice) {
        this.highestPrice = highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.LOWEST_PRICE
     *
     * @return the value of PRODUCT_QUOTE.LOWEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getLowestPrice() {
        return lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.LOWEST_PRICE
     *
     * @param lowestPrice the value for PRODUCT_QUOTE.LOWEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setLowestPrice(Double lowestPrice) {
        this.lowestPrice = lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @return the value of PRODUCT_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCompetitiveBuyPrice() {
        return competitiveBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @param competitiveBuyPrice the value for PRODUCT_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCompetitiveBuyPrice(Double competitiveBuyPrice) {
        this.competitiveBuyPrice = competitiveBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @return the value of PRODUCT_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCompetitiveSalePrice() {
        return competitiveSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @param competitiveSalePrice the value for PRODUCT_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCompetitiveSalePrice(Double competitiveSalePrice) {
        this.competitiveSalePrice = competitiveSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.NUMBER_OF_HELD
     *
     * @return the value of PRODUCT_QUOTE.NUMBER_OF_HELD
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getNumberOfHeld() {
        return numberOfHeld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.NUMBER_OF_HELD
     *
     * @param numberOfHeld the value for PRODUCT_QUOTE.NUMBER_OF_HELD
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setNumberOfHeld(Long numberOfHeld) {
        this.numberOfHeld = numberOfHeld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.NUMBER_OF_TRADED
     *
     * @return the value of PRODUCT_QUOTE.NUMBER_OF_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getNumberOfTraded() {
        return numberOfTraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.NUMBER_OF_TRADED
     *
     * @param numberOfTraded the value for PRODUCT_QUOTE.NUMBER_OF_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setNumberOfTraded(Long numberOfTraded) {
        this.numberOfTraded = numberOfTraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.AMOUNT_OF_BUY
     *
     * @return the value of PRODUCT_QUOTE.AMOUNT_OF_BUY
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfBuy() {
        return amountOfBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.AMOUNT_OF_BUY
     *
     * @param amountOfBuy the value for PRODUCT_QUOTE.AMOUNT_OF_BUY
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfBuy(Long amountOfBuy) {
        this.amountOfBuy = amountOfBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY1
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy1() {
        return priceOfBuy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY1
     *
     * @param priceOfBuy1 the value for PRODUCT_QUOTE.PRICE_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy1(Double priceOfBuy1) {
        this.priceOfBuy1 = priceOfBuy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY2
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy2() {
        return priceOfBuy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY2
     *
     * @param priceOfBuy2 the value for PRODUCT_QUOTE.PRICE_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy2(Double priceOfBuy2) {
        this.priceOfBuy2 = priceOfBuy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY3
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy3() {
        return priceOfBuy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY3
     *
     * @param priceOfBuy3 the value for PRODUCT_QUOTE.PRICE_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy3(Double priceOfBuy3) {
        this.priceOfBuy3 = priceOfBuy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY4
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy4() {
        return priceOfBuy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY4
     *
     * @param priceOfBuy4 the value for PRODUCT_QUOTE.PRICE_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy4(Double priceOfBuy4) {
        this.priceOfBuy4 = priceOfBuy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY5
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy5() {
        return priceOfBuy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_BUY5
     *
     * @param priceOfBuy5 the value for PRODUCT_QUOTE.PRICE_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy5(Double priceOfBuy5) {
        this.priceOfBuy5 = priceOfBuy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.AMOUNT_OF_SALE
     *
     * @return the value of PRODUCT_QUOTE.AMOUNT_OF_SALE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfSale() {
        return amountOfSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.AMOUNT_OF_SALE
     *
     * @param amountOfSale the value for PRODUCT_QUOTE.AMOUNT_OF_SALE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfSale(Long amountOfSale) {
        this.amountOfSale = amountOfSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE1
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale1() {
        return priceOfSale1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE1
     *
     * @param priceOfSale1 the value for PRODUCT_QUOTE.PRICE_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale1(Double priceOfSale1) {
        this.priceOfSale1 = priceOfSale1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE2
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale2() {
        return priceOfSale2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE2
     *
     * @param priceOfSale2 the value for PRODUCT_QUOTE.PRICE_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale2(Double priceOfSale2) {
        this.priceOfSale2 = priceOfSale2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE3
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale3() {
        return priceOfSale3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE3
     *
     * @param priceOfSale3 the value for PRODUCT_QUOTE.PRICE_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale3(Double priceOfSale3) {
        this.priceOfSale3 = priceOfSale3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE4
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale4() {
        return priceOfSale4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE4
     *
     * @param priceOfSale4 the value for PRODUCT_QUOTE.PRICE_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale4(Double priceOfSale4) {
        this.priceOfSale4 = priceOfSale4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE5
     *
     * @return the value of PRODUCT_QUOTE.PRICE_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale5() {
        return priceOfSale5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.PRICE_OF_SALE5
     *
     * @param priceOfSale5 the value for PRODUCT_QUOTE.PRICE_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale5(Double priceOfSale5) {
        this.priceOfSale5 = priceOfSale5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.DATE
     *
     * @return the value of PRODUCT_QUOTE.DATE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.DATE
     *
     * @param date the value for PRODUCT_QUOTE.DATE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.TIME
     *
     * @return the value of PRODUCT_QUOTE.TIME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.TIME
     *
     * @param time the value for PRODUCT_QUOTE.TIME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.SYMBOL
     *
     * @return the value of PRODUCT_QUOTE.SYMBOL
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.SYMBOL
     *
     * @param symbol the value for PRODUCT_QUOTE.SYMBOL
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.SETTLEMENT_PRICE
     *
     * @return the value of PRODUCT_QUOTE.SETTLEMENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.SETTLEMENT_PRICE
     *
     * @param settlementPrice the value for PRODUCT_QUOTE.SETTLEMENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setSettlementPrice(Double settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.LAST_SETTLEMENT_PRICE
     *
     * @return the value of PRODUCT_QUOTE.LAST_SETTLEMENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getLastSettlementPrice() {
        return lastSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.LAST_SETTLEMENT_PRICE
     *
     * @param lastSettlementPrice the value for PRODUCT_QUOTE.LAST_SETTLEMENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setLastSettlementPrice(Double lastSettlementPrice) {
        this.lastSettlementPrice = lastSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.EXCHANGE
     *
     * @return the value of PRODUCT_QUOTE.EXCHANGE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.EXCHANGE
     *
     * @param exchange the value for PRODUCT_QUOTE.EXCHANGE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_QUOTE.CATEGORY
     *
     * @return the value of PRODUCT_QUOTE.CATEGORY
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_QUOTE.CATEGORY
     *
     * @param category the value for PRODUCT_QUOTE.CATEGORY
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}