package com.connect.quant.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table STOCK_QUOTE
 *
 * @mbg.generated do_not_delete_during_merge Fri Aug 03 11:21:49 CST 2018
 */
public class StockQuote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.ID
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.NAME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.OPENINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double openingprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.CLOSINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double closingprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.CURRENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double currentprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.HIGHESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double highestprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.LOWESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double lowestprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.COMPETITIVEBUYPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double competitivebuyprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.COMPETITIVESALEPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double competitivesaleprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.NUMBEROFSHARETRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long numberofsharetraded;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.MONEYOFSHARETRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double moneyofsharetraded;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofbuy1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofbuy2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofbuy3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofbuy4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofbuy5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofbuy5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofsale1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofsale2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofsale3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofsale4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.AMOUNTOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Long amountofsale5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.PRICEOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Double priceofsale5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.DATE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.TIME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column STOCK_QUOTE.SNO
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	private String sno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.ID
	 * @return  the value of STOCK_QUOTE.ID
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.ID
	 * @param id  the value for STOCK_QUOTE.ID
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.NAME
	 * @return  the value of STOCK_QUOTE.NAME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.NAME
	 * @param name  the value for STOCK_QUOTE.NAME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.OPENINGPRICE
	 * @return  the value of STOCK_QUOTE.OPENINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getOpeningprice() {
		return openingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.OPENINGPRICE
	 * @param openingprice  the value for STOCK_QUOTE.OPENINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setOpeningprice(Double openingprice) {
		this.openingprice = openingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.CLOSINGPRICE
	 * @return  the value of STOCK_QUOTE.CLOSINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getClosingprice() {
		return closingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.CLOSINGPRICE
	 * @param closingprice  the value for STOCK_QUOTE.CLOSINGPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setClosingprice(Double closingprice) {
		this.closingprice = closingprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.CURRENTPRICE
	 * @return  the value of STOCK_QUOTE.CURRENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getCurrentprice() {
		return currentprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.CURRENTPRICE
	 * @param currentprice  the value for STOCK_QUOTE.CURRENTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCurrentprice(Double currentprice) {
		this.currentprice = currentprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.HIGHESTPRICE
	 * @return  the value of STOCK_QUOTE.HIGHESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getHighestprice() {
		return highestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.HIGHESTPRICE
	 * @param highestprice  the value for STOCK_QUOTE.HIGHESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setHighestprice(Double highestprice) {
		this.highestprice = highestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.LOWESTPRICE
	 * @return  the value of STOCK_QUOTE.LOWESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getLowestprice() {
		return lowestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.LOWESTPRICE
	 * @param lowestprice  the value for STOCK_QUOTE.LOWESTPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setLowestprice(Double lowestprice) {
		this.lowestprice = lowestprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.COMPETITIVEBUYPRICE
	 * @return  the value of STOCK_QUOTE.COMPETITIVEBUYPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getCompetitivebuyprice() {
		return competitivebuyprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.COMPETITIVEBUYPRICE
	 * @param competitivebuyprice  the value for STOCK_QUOTE.COMPETITIVEBUYPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCompetitivebuyprice(Double competitivebuyprice) {
		this.competitivebuyprice = competitivebuyprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.COMPETITIVESALEPRICE
	 * @return  the value of STOCK_QUOTE.COMPETITIVESALEPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getCompetitivesaleprice() {
		return competitivesaleprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.COMPETITIVESALEPRICE
	 * @param competitivesaleprice  the value for STOCK_QUOTE.COMPETITIVESALEPRICE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setCompetitivesaleprice(Double competitivesaleprice) {
		this.competitivesaleprice = competitivesaleprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.NUMBEROFSHARETRADED
	 * @return  the value of STOCK_QUOTE.NUMBEROFSHARETRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getNumberofsharetraded() {
		return numberofsharetraded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.NUMBEROFSHARETRADED
	 * @param numberofsharetraded  the value for STOCK_QUOTE.NUMBEROFSHARETRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setNumberofsharetraded(Long numberofsharetraded) {
		this.numberofsharetraded = numberofsharetraded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.MONEYOFSHARETRADED
	 * @return  the value of STOCK_QUOTE.MONEYOFSHARETRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getMoneyofsharetraded() {
		return moneyofsharetraded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.MONEYOFSHARETRADED
	 * @param moneyofsharetraded  the value for STOCK_QUOTE.MONEYOFSHARETRADED
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setMoneyofsharetraded(Double moneyofsharetraded) {
		this.moneyofsharetraded = moneyofsharetraded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFBUY1
	 * @return  the value of STOCK_QUOTE.AMOUNTOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofbuy1() {
		return amountofbuy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFBUY1
	 * @param amountofbuy1  the value for STOCK_QUOTE.AMOUNTOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofbuy1(Long amountofbuy1) {
		this.amountofbuy1 = amountofbuy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFBUY1
	 * @return  the value of STOCK_QUOTE.PRICEOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy1() {
		return priceofbuy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFBUY1
	 * @param priceofbuy1  the value for STOCK_QUOTE.PRICEOFBUY1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy1(Double priceofbuy1) {
		this.priceofbuy1 = priceofbuy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFBUY2
	 * @return  the value of STOCK_QUOTE.AMOUNTOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofbuy2() {
		return amountofbuy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFBUY2
	 * @param amountofbuy2  the value for STOCK_QUOTE.AMOUNTOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofbuy2(Long amountofbuy2) {
		this.amountofbuy2 = amountofbuy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFBUY2
	 * @return  the value of STOCK_QUOTE.PRICEOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy2() {
		return priceofbuy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFBUY2
	 * @param priceofbuy2  the value for STOCK_QUOTE.PRICEOFBUY2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy2(Double priceofbuy2) {
		this.priceofbuy2 = priceofbuy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFBUY3
	 * @return  the value of STOCK_QUOTE.AMOUNTOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofbuy3() {
		return amountofbuy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFBUY3
	 * @param amountofbuy3  the value for STOCK_QUOTE.AMOUNTOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofbuy3(Long amountofbuy3) {
		this.amountofbuy3 = amountofbuy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFBUY3
	 * @return  the value of STOCK_QUOTE.PRICEOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy3() {
		return priceofbuy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFBUY3
	 * @param priceofbuy3  the value for STOCK_QUOTE.PRICEOFBUY3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy3(Double priceofbuy3) {
		this.priceofbuy3 = priceofbuy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFBUY4
	 * @return  the value of STOCK_QUOTE.AMOUNTOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofbuy4() {
		return amountofbuy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFBUY4
	 * @param amountofbuy4  the value for STOCK_QUOTE.AMOUNTOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofbuy4(Long amountofbuy4) {
		this.amountofbuy4 = amountofbuy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFBUY4
	 * @return  the value of STOCK_QUOTE.PRICEOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy4() {
		return priceofbuy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFBUY4
	 * @param priceofbuy4  the value for STOCK_QUOTE.PRICEOFBUY4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy4(Double priceofbuy4) {
		this.priceofbuy4 = priceofbuy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFBUY5
	 * @return  the value of STOCK_QUOTE.AMOUNTOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofbuy5() {
		return amountofbuy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFBUY5
	 * @param amountofbuy5  the value for STOCK_QUOTE.AMOUNTOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofbuy5(Long amountofbuy5) {
		this.amountofbuy5 = amountofbuy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFBUY5
	 * @return  the value of STOCK_QUOTE.PRICEOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofbuy5() {
		return priceofbuy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFBUY5
	 * @param priceofbuy5  the value for STOCK_QUOTE.PRICEOFBUY5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofbuy5(Double priceofbuy5) {
		this.priceofbuy5 = priceofbuy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFSALE1
	 * @return  the value of STOCK_QUOTE.AMOUNTOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofsale1() {
		return amountofsale1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFSALE1
	 * @param amountofsale1  the value for STOCK_QUOTE.AMOUNTOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofsale1(Long amountofsale1) {
		this.amountofsale1 = amountofsale1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFSALE1
	 * @return  the value of STOCK_QUOTE.PRICEOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale1() {
		return priceofsale1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFSALE1
	 * @param priceofsale1  the value for STOCK_QUOTE.PRICEOFSALE1
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale1(Double priceofsale1) {
		this.priceofsale1 = priceofsale1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFSALE2
	 * @return  the value of STOCK_QUOTE.AMOUNTOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofsale2() {
		return amountofsale2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFSALE2
	 * @param amountofsale2  the value for STOCK_QUOTE.AMOUNTOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofsale2(Long amountofsale2) {
		this.amountofsale2 = amountofsale2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFSALE2
	 * @return  the value of STOCK_QUOTE.PRICEOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale2() {
		return priceofsale2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFSALE2
	 * @param priceofsale2  the value for STOCK_QUOTE.PRICEOFSALE2
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale2(Double priceofsale2) {
		this.priceofsale2 = priceofsale2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFSALE3
	 * @return  the value of STOCK_QUOTE.AMOUNTOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofsale3() {
		return amountofsale3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFSALE3
	 * @param amountofsale3  the value for STOCK_QUOTE.AMOUNTOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofsale3(Long amountofsale3) {
		this.amountofsale3 = amountofsale3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFSALE3
	 * @return  the value of STOCK_QUOTE.PRICEOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale3() {
		return priceofsale3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFSALE3
	 * @param priceofsale3  the value for STOCK_QUOTE.PRICEOFSALE3
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale3(Double priceofsale3) {
		this.priceofsale3 = priceofsale3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFSALE4
	 * @return  the value of STOCK_QUOTE.AMOUNTOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofsale4() {
		return amountofsale4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFSALE4
	 * @param amountofsale4  the value for STOCK_QUOTE.AMOUNTOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofsale4(Long amountofsale4) {
		this.amountofsale4 = amountofsale4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFSALE4
	 * @return  the value of STOCK_QUOTE.PRICEOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale4() {
		return priceofsale4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFSALE4
	 * @param priceofsale4  the value for STOCK_QUOTE.PRICEOFSALE4
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale4(Double priceofsale4) {
		this.priceofsale4 = priceofsale4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.AMOUNTOFSALE5
	 * @return  the value of STOCK_QUOTE.AMOUNTOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Long getAmountofsale5() {
		return amountofsale5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.AMOUNTOFSALE5
	 * @param amountofsale5  the value for STOCK_QUOTE.AMOUNTOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setAmountofsale5(Long amountofsale5) {
		this.amountofsale5 = amountofsale5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.PRICEOFSALE5
	 * @return  the value of STOCK_QUOTE.PRICEOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Double getPriceofsale5() {
		return priceofsale5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.PRICEOFSALE5
	 * @param priceofsale5  the value for STOCK_QUOTE.PRICEOFSALE5
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setPriceofsale5(Double priceofsale5) {
		this.priceofsale5 = priceofsale5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.DATE
	 * @return  the value of STOCK_QUOTE.DATE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.DATE
	 * @param date  the value for STOCK_QUOTE.DATE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.TIME
	 * @return  the value of STOCK_QUOTE.TIME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.TIME
	 * @param time  the value for STOCK_QUOTE.TIME
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column STOCK_QUOTE.SNO
	 * @return  the value of STOCK_QUOTE.SNO
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public String getSno() {
		return sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column STOCK_QUOTE.SNO
	 * @param sno  the value for STOCK_QUOTE.SNO
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	public void setSno(String sno) {
		this.sno = sno == null ? null : sno.trim();
	}
}