package com.connect.quant.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table STOCK_QUOTE
 *
 * @mbg.generated do_not_delete_during_merge Tue Aug 07 14:58:26 CST 2018
 */
public class StockQuote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.SYMBOL
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.NAME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.OPENING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double openingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.CLOSING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double closingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.CURRENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double currentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.HIGHEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double highestPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.LOWEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double lowestPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double competitiveBuyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double competitiveSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.NUMBER_OF_SHARE_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long numberOfShareTraded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.MONEY_OF_SHARE_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double moneyOfShareTraded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfBuy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfBuy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfBuy3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfBuy4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfBuy5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfBuy5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfSale1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfSale2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfSale3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfSale4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.AMOUNT_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Long amountOfSale5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.PRICE_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Double priceOfSale5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.EXCHANGE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.DATE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_QUOTE.TIME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.SNO
     *
     * @return the value of STOCK_QUOTE.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.SNO
     *
     * @param sno the value for STOCK_QUOTE.SNO
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.SYMBOL
     *
     * @return the value of STOCK_QUOTE.SYMBOL
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.SYMBOL
     *
     * @param symbol the value for STOCK_QUOTE.SYMBOL
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.NAME
     *
     * @return the value of STOCK_QUOTE.NAME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.NAME
     *
     * @param name the value for STOCK_QUOTE.NAME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.OPENING_PRICE
     *
     * @return the value of STOCK_QUOTE.OPENING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getOpeningPrice() {
        return openingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.OPENING_PRICE
     *
     * @param openingPrice the value for STOCK_QUOTE.OPENING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setOpeningPrice(Double openingPrice) {
        this.openingPrice = openingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.CLOSING_PRICE
     *
     * @return the value of STOCK_QUOTE.CLOSING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getClosingPrice() {
        return closingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.CLOSING_PRICE
     *
     * @param closingPrice the value for STOCK_QUOTE.CLOSING_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setClosingPrice(Double closingPrice) {
        this.closingPrice = closingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.CURRENT_PRICE
     *
     * @return the value of STOCK_QUOTE.CURRENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.CURRENT_PRICE
     *
     * @param currentPrice the value for STOCK_QUOTE.CURRENT_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.HIGHEST_PRICE
     *
     * @return the value of STOCK_QUOTE.HIGHEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getHighestPrice() {
        return highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.HIGHEST_PRICE
     *
     * @param highestPrice the value for STOCK_QUOTE.HIGHEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setHighestPrice(Double highestPrice) {
        this.highestPrice = highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.LOWEST_PRICE
     *
     * @return the value of STOCK_QUOTE.LOWEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getLowestPrice() {
        return lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.LOWEST_PRICE
     *
     * @param lowestPrice the value for STOCK_QUOTE.LOWEST_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setLowestPrice(Double lowestPrice) {
        this.lowestPrice = lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @return the value of STOCK_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCompetitiveBuyPrice() {
        return competitiveBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @param competitiveBuyPrice the value for STOCK_QUOTE.COMPETITIVE_BUY_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCompetitiveBuyPrice(Double competitiveBuyPrice) {
        this.competitiveBuyPrice = competitiveBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @return the value of STOCK_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getCompetitiveSalePrice() {
        return competitiveSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @param competitiveSalePrice the value for STOCK_QUOTE.COMPETITIVE_SALE_PRICE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setCompetitiveSalePrice(Double competitiveSalePrice) {
        this.competitiveSalePrice = competitiveSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.NUMBER_OF_SHARE_TRADED
     *
     * @return the value of STOCK_QUOTE.NUMBER_OF_SHARE_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getNumberOfShareTraded() {
        return numberOfShareTraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.NUMBER_OF_SHARE_TRADED
     *
     * @param numberOfShareTraded the value for STOCK_QUOTE.NUMBER_OF_SHARE_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setNumberOfShareTraded(Long numberOfShareTraded) {
        this.numberOfShareTraded = numberOfShareTraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.MONEY_OF_SHARE_TRADED
     *
     * @return the value of STOCK_QUOTE.MONEY_OF_SHARE_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getMoneyOfShareTraded() {
        return moneyOfShareTraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.MONEY_OF_SHARE_TRADED
     *
     * @param moneyOfShareTraded the value for STOCK_QUOTE.MONEY_OF_SHARE_TRADED
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setMoneyOfShareTraded(Double moneyOfShareTraded) {
        this.moneyOfShareTraded = moneyOfShareTraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY1
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfBuy1() {
        return amountOfBuy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY1
     *
     * @param amountOfBuy1 the value for STOCK_QUOTE.AMOUNT_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfBuy1(Long amountOfBuy1) {
        this.amountOfBuy1 = amountOfBuy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_BUY1
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy1() {
        return priceOfBuy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_BUY1
     *
     * @param priceOfBuy1 the value for STOCK_QUOTE.PRICE_OF_BUY1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy1(Double priceOfBuy1) {
        this.priceOfBuy1 = priceOfBuy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY2
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfBuy2() {
        return amountOfBuy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY2
     *
     * @param amountOfBuy2 the value for STOCK_QUOTE.AMOUNT_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfBuy2(Long amountOfBuy2) {
        this.amountOfBuy2 = amountOfBuy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_BUY2
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy2() {
        return priceOfBuy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_BUY2
     *
     * @param priceOfBuy2 the value for STOCK_QUOTE.PRICE_OF_BUY2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy2(Double priceOfBuy2) {
        this.priceOfBuy2 = priceOfBuy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY3
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfBuy3() {
        return amountOfBuy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY3
     *
     * @param amountOfBuy3 the value for STOCK_QUOTE.AMOUNT_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfBuy3(Long amountOfBuy3) {
        this.amountOfBuy3 = amountOfBuy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_BUY3
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy3() {
        return priceOfBuy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_BUY3
     *
     * @param priceOfBuy3 the value for STOCK_QUOTE.PRICE_OF_BUY3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy3(Double priceOfBuy3) {
        this.priceOfBuy3 = priceOfBuy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY4
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfBuy4() {
        return amountOfBuy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY4
     *
     * @param amountOfBuy4 the value for STOCK_QUOTE.AMOUNT_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfBuy4(Long amountOfBuy4) {
        this.amountOfBuy4 = amountOfBuy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_BUY4
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy4() {
        return priceOfBuy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_BUY4
     *
     * @param priceOfBuy4 the value for STOCK_QUOTE.PRICE_OF_BUY4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy4(Double priceOfBuy4) {
        this.priceOfBuy4 = priceOfBuy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY5
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfBuy5() {
        return amountOfBuy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_BUY5
     *
     * @param amountOfBuy5 the value for STOCK_QUOTE.AMOUNT_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfBuy5(Long amountOfBuy5) {
        this.amountOfBuy5 = amountOfBuy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_BUY5
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfBuy5() {
        return priceOfBuy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_BUY5
     *
     * @param priceOfBuy5 the value for STOCK_QUOTE.PRICE_OF_BUY5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfBuy5(Double priceOfBuy5) {
        this.priceOfBuy5 = priceOfBuy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE1
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfSale1() {
        return amountOfSale1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE1
     *
     * @param amountOfSale1 the value for STOCK_QUOTE.AMOUNT_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfSale1(Long amountOfSale1) {
        this.amountOfSale1 = amountOfSale1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_SALE1
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale1() {
        return priceOfSale1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_SALE1
     *
     * @param priceOfSale1 the value for STOCK_QUOTE.PRICE_OF_SALE1
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale1(Double priceOfSale1) {
        this.priceOfSale1 = priceOfSale1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE2
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfSale2() {
        return amountOfSale2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE2
     *
     * @param amountOfSale2 the value for STOCK_QUOTE.AMOUNT_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfSale2(Long amountOfSale2) {
        this.amountOfSale2 = amountOfSale2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_SALE2
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale2() {
        return priceOfSale2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_SALE2
     *
     * @param priceOfSale2 the value for STOCK_QUOTE.PRICE_OF_SALE2
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale2(Double priceOfSale2) {
        this.priceOfSale2 = priceOfSale2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE3
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfSale3() {
        return amountOfSale3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE3
     *
     * @param amountOfSale3 the value for STOCK_QUOTE.AMOUNT_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfSale3(Long amountOfSale3) {
        this.amountOfSale3 = amountOfSale3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_SALE3
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale3() {
        return priceOfSale3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_SALE3
     *
     * @param priceOfSale3 the value for STOCK_QUOTE.PRICE_OF_SALE3
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale3(Double priceOfSale3) {
        this.priceOfSale3 = priceOfSale3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE4
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfSale4() {
        return amountOfSale4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE4
     *
     * @param amountOfSale4 the value for STOCK_QUOTE.AMOUNT_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfSale4(Long amountOfSale4) {
        this.amountOfSale4 = amountOfSale4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_SALE4
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale4() {
        return priceOfSale4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_SALE4
     *
     * @param priceOfSale4 the value for STOCK_QUOTE.PRICE_OF_SALE4
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale4(Double priceOfSale4) {
        this.priceOfSale4 = priceOfSale4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE5
     *
     * @return the value of STOCK_QUOTE.AMOUNT_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Long getAmountOfSale5() {
        return amountOfSale5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.AMOUNT_OF_SALE5
     *
     * @param amountOfSale5 the value for STOCK_QUOTE.AMOUNT_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setAmountOfSale5(Long amountOfSale5) {
        this.amountOfSale5 = amountOfSale5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.PRICE_OF_SALE5
     *
     * @return the value of STOCK_QUOTE.PRICE_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Double getPriceOfSale5() {
        return priceOfSale5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.PRICE_OF_SALE5
     *
     * @param priceOfSale5 the value for STOCK_QUOTE.PRICE_OF_SALE5
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setPriceOfSale5(Double priceOfSale5) {
        this.priceOfSale5 = priceOfSale5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.EXCHANGE
     *
     * @return the value of STOCK_QUOTE.EXCHANGE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.EXCHANGE
     *
     * @param exchange the value for STOCK_QUOTE.EXCHANGE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.DATE
     *
     * @return the value of STOCK_QUOTE.DATE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.DATE
     *
     * @param date the value for STOCK_QUOTE.DATE
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_QUOTE.TIME
     *
     * @return the value of STOCK_QUOTE.TIME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_QUOTE.TIME
     *
     * @param time the value for STOCK_QUOTE.TIME
     *
     * @mbg.generated Tue Aug 07 14:58:26 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}