package com.connect.quant.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TICK
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 15 21:50:48 CST 2018
 */
public class Tick {

    private Integer sno;
    /** 合约代码 */
    private String symbol;
    /** 交易所代码 */
    private String exchange;
    /** 合约在vt系统中的唯一代码，通常是 合约代码.交易所代码 */
    private String vtSymbol;

    /**成交数据*/
    /** 最新成交价 */
    private double lastPrice;
    /** 最新成交量 */
    private long lastVolume;
    /** 今天总成交量 */
    private long volume;
    /** 持仓量 */
    private long openlongerest;
    /** 时间 11:20:56.5 */
    private String time;
    /** 日期 20151009 */
    private String date;
    /**python的datetime时间对象*/
    private String datetime;

    /**常规行情*/
    /** 今日开盘价 */
    private double openPrice;
    /** 今日最高价 */
    private double highPrice;
    /** 今日最低价 */
    private double lowPrice;
    /** 昨日收盘价*/
    private double preClosePrice;

    /** 涨停价 */
    private double upperLimit;
    /** 跌停价 */
    private double lowerLimit;

    /**五档行情*/
    private double bidPrice1;
    private double bidPrice2;
    private double bidPrice3;
    private double bidPrice4;
    private double bidPrice5;

    private double askPrice1;
    private double askPrice2;
    private double askPrice3;
    private double askPrice4;
    private double askPrice5;

    private long bidVolume1;
    private long bidVolume2;
    private long bidVolume3;
    private long bidVolume4;
    private long bidVolume5;

    private long askVolume1;
    private long askVolume2;
    private long askVolume3;
    private long askVolume4;
    private long askVolume5;

    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.SNO
     *
     * @param sno the value for TICK.SNO
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.SYMBOL
     *
     * @return the value of TICK.SYMBOL
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.SYMBOL
     *
     * @param symbol the value for TICK.SYMBOL
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.EXCHANGE
     *
     * @return the value of TICK.EXCHANGE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.EXCHANGE
     *
     * @param exchange the value for TICK.EXCHANGE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.VT_SYMBOL
     *
     * @return the value of TICK.VT_SYMBOL
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public String getVtSymbol() {
        return vtSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.VT_SYMBOL
     *
     * @param vtSymbol the value for TICK.VT_SYMBOL
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setVtSymbol(String vtSymbol) {
        this.vtSymbol = vtSymbol == null ? null : vtSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.LAST_PRICE
     *
     * @return the value of TICK.LAST_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getLastPrice() {
        return lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.LAST_PRICE
     *
     * @param lastPrice the value for TICK.LAST_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setLastPrice(Double lastPrice) {
        this.lastPrice = lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.LAST_VOLUME
     *
     * @return the value of TICK.LAST_VOLUME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getLastVolume() {
        return lastVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.LAST_VOLUME
     *
     * @param lastVolume the value for TICK.LAST_VOLUME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setLastVolume(Long lastVolume) {
        this.lastVolume = lastVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.VOLUME
     *
     * @return the value of TICK.VOLUME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.VOLUME
     *
     * @param volume the value for TICK.VOLUME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.OPENLONGEREST
     *
     * @return the value of TICK.OPENLONGEREST
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getOpenlongerest() {
        return openlongerest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.OPENLONGEREST
     *
     * @param openlongerest the value for TICK.OPENLONGEREST
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setOpenlongerest(Long openlongerest) {
        this.openlongerest = openlongerest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.TIME
     *
     * @return the value of TICK.TIME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.TIME
     *
     * @param time the value for TICK.TIME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.DATE
     *
     * @return the value of TICK.DATE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.DATE
     *
     * @param date the value for TICK.DATE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.DATETIME
     *
     * @return the value of TICK.DATETIME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.DATETIME
     *
     * @param datetime the value for TICK.DATETIME
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setDatetime(String datetime) {
        this.datetime = datetime == null ? null : datetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.OPEN_PRICE
     *
     * @return the value of TICK.OPEN_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.OPEN_PRICE
     *
     * @param openPrice the value for TICK.OPEN_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setOpenPrice(Double openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.HIGH_PRICE
     *
     * @return the value of TICK.HIGH_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.HIGH_PRICE
     *
     * @param highPrice the value for TICK.HIGH_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setHighPrice(Double highPrice) {
        this.highPrice = highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.LOW_PRICE
     *
     * @return the value of TICK.LOW_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.LOW_PRICE
     *
     * @param lowPrice the value for TICK.LOW_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setLowPrice(Double lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.PRE_CLOSE_PRICE
     *
     * @return the value of TICK.PRE_CLOSE_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getPreClosePrice() {
        return preClosePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.PRE_CLOSE_PRICE
     *
     * @param preClosePrice the value for TICK.PRE_CLOSE_PRICE
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setPreClosePrice(Double preClosePrice) {
        this.preClosePrice = preClosePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.UPPER_LIMIT
     *
     * @return the value of TICK.UPPER_LIMIT
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.UPPER_LIMIT
     *
     * @param upperLimit the value for TICK.UPPER_LIMIT
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setUpperLimit(Double upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.LOWER_LIMIT
     *
     * @return the value of TICK.LOWER_LIMIT
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getLowerLimit() {
        return lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.LOWER_LIMIT
     *
     * @param lowerLimit the value for TICK.LOWER_LIMIT
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setLowerLimit(Double lowerLimit) {
        this.lowerLimit = lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_PRICE1
     *
     * @return the value of TICK.BID_PRICE1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getBidPrice1() {
        return bidPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_PRICE1
     *
     * @param bidPrice1 the value for TICK.BID_PRICE1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidPrice1(Double bidPrice1) {
        this.bidPrice1 = bidPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_PRICE2
     *
     * @return the value of TICK.BID_PRICE2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getBidPrice2() {
        return bidPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_PRICE2
     *
     * @param bidPrice2 the value for TICK.BID_PRICE2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidPrice2(Double bidPrice2) {
        this.bidPrice2 = bidPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_PRICE3
     *
     * @return the value of TICK.BID_PRICE3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getBidPrice3() {
        return bidPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_PRICE3
     *
     * @param bidPrice3 the value for TICK.BID_PRICE3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidPrice3(Double bidPrice3) {
        this.bidPrice3 = bidPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_PRICE4
     *
     * @return the value of TICK.BID_PRICE4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getBidPrice4() {
        return bidPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_PRICE4
     *
     * @param bidPrice4 the value for TICK.BID_PRICE4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidPrice4(Double bidPrice4) {
        this.bidPrice4 = bidPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_PRICE5
     *
     * @return the value of TICK.BID_PRICE5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getBidPrice5() {
        return bidPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_PRICE5
     *
     * @param bidPrice5 the value for TICK.BID_PRICE5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidPrice5(Double bidPrice5) {
        this.bidPrice5 = bidPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_PRICE1
     *
     * @return the value of TICK.ASK_PRICE1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getAskPrice1() {
        return askPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_PRICE1
     *
     * @param askPrice1 the value for TICK.ASK_PRICE1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskPrice1(Double askPrice1) {
        this.askPrice1 = askPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_PRICE2
     *
     * @return the value of TICK.ASK_PRICE2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getAskPrice2() {
        return askPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_PRICE2
     *
     * @param askPrice2 the value for TICK.ASK_PRICE2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskPrice2(Double askPrice2) {
        this.askPrice2 = askPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_PRICE3
     *
     * @return the value of TICK.ASK_PRICE3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getAskPrice3() {
        return askPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_PRICE3
     *
     * @param askPrice3 the value for TICK.ASK_PRICE3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskPrice3(Double askPrice3) {
        this.askPrice3 = askPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_PRICE4
     *
     * @return the value of TICK.ASK_PRICE4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getAskPrice4() {
        return askPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_PRICE4
     *
     * @param askPrice4 the value for TICK.ASK_PRICE4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskPrice4(Double askPrice4) {
        this.askPrice4 = askPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_PRICE5
     *
     * @return the value of TICK.ASK_PRICE5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Double getAskPrice5() {
        return askPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_PRICE5
     *
     * @param askPrice5 the value for TICK.ASK_PRICE5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskPrice5(Double askPrice5) {
        this.askPrice5 = askPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_VOLUME1
     *
     * @return the value of TICK.BID_VOLUME1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getBidVolume1() {
        return bidVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_VOLUME1
     *
     * @param bidVolume1 the value for TICK.BID_VOLUME1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidVolume1(Long bidVolume1) {
        this.bidVolume1 = bidVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_VOLUME2
     *
     * @return the value of TICK.BID_VOLUME2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getBidVolume2() {
        return bidVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_VOLUME2
     *
     * @param bidVolume2 the value for TICK.BID_VOLUME2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidVolume2(Long bidVolume2) {
        this.bidVolume2 = bidVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_VOLUME3
     *
     * @return the value of TICK.BID_VOLUME3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getBidVolume3() {
        return bidVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_VOLUME3
     *
     * @param bidVolume3 the value for TICK.BID_VOLUME3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidVolume3(Long bidVolume3) {
        this.bidVolume3 = bidVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_VOLUME4
     *
     * @return the value of TICK.BID_VOLUME4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getBidVolume4() {
        return bidVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_VOLUME4
     *
     * @param bidVolume4 the value for TICK.BID_VOLUME4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidVolume4(Long bidVolume4) {
        this.bidVolume4 = bidVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.BID_VOLUME5
     *
     * @return the value of TICK.BID_VOLUME5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getBidVolume5() {
        return bidVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.BID_VOLUME5
     *
     * @param bidVolume5 the value for TICK.BID_VOLUME5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setBidVolume5(Long bidVolume5) {
        this.bidVolume5 = bidVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_VOLUME1
     *
     * @return the value of TICK.ASK_VOLUME1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getAskVolume1() {
        return askVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_VOLUME1
     *
     * @param askVolume1 the value for TICK.ASK_VOLUME1
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskVolume1(Long askVolume1) {
        this.askVolume1 = askVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_VOLUME2
     *
     * @return the value of TICK.ASK_VOLUME2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getAskVolume2() {
        return askVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_VOLUME2
     *
     * @param askVolume2 the value for TICK.ASK_VOLUME2
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskVolume2(Long askVolume2) {
        this.askVolume2 = askVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_VOLUME3
     *
     * @return the value of TICK.ASK_VOLUME3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getAskVolume3() {
        return askVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_VOLUME3
     *
     * @param askVolume3 the value for TICK.ASK_VOLUME3
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskVolume3(Long askVolume3) {
        this.askVolume3 = askVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_VOLUME4
     *
     * @return the value of TICK.ASK_VOLUME4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getAskVolume4() {
        return askVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_VOLUME4
     *
     * @param askVolume4 the value for TICK.ASK_VOLUME4
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskVolume4(Long askVolume4) {
        this.askVolume4 = askVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TICK.ASK_VOLUME5
     *
     * @return the value of TICK.ASK_VOLUME5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public Long getAskVolume5() {
        return askVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TICK.ASK_VOLUME5
     *
     * @param askVolume5 the value for TICK.ASK_VOLUME5
     *
     * @mbg.generated Wed Aug 15 21:50:48 CST 2018
     */
    public void setAskVolume5(Long askVolume5) {
        this.askVolume5 = askVolume5;
    }
}