package com.connect.quant.dao.mapper;

import com.connect.quant.model.Account;
import com.connect.quant.model.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	long countByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int deleteByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int deleteByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int insertSelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	List<Account> selectByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	Account selectByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByPrimaryKeySelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ACCOUNT
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByPrimaryKey(Account record);
}