package com.connect.quant.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.connect.quant.model.Bar;
import com.connect.quant.model.BarExample;

public interface BarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	long countByExample(BarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int deleteByExample(BarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int insert(Bar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int insertSelective(Bar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	List<Bar> selectByExample(BarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	Bar selectByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Bar record, @Param("example") BarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByExample(@Param("record") Bar record, @Param("example") BarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByPrimaryKeySelective(Bar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAR
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByPrimaryKey(Bar record);
}