package com.connect.quant.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.connect.quant.model.FutureQuote;
import com.connect.quant.model.FutureQuoteExample;

@Repository
public interface FutureQuoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	long countByExample(FutureQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int deleteByExample(FutureQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int deleteByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int insert(FutureQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int insertSelective(FutureQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	List<FutureQuote> selectByExample(FutureQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	FutureQuote selectByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int updateByExampleSelective(@Param("record") FutureQuote record, @Param("example") FutureQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int updateByExample(@Param("record") FutureQuote record, @Param("example") FutureQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int updateByPrimaryKeySelective(FutureQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUTURE_QUOTE
	 * @mbg.generated  Fri Aug 17 14:00:14 CST 2018
	 */
	int updateByPrimaryKey(FutureQuote record);
}