package com.connect.quant.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.connect.quant.model.ProductQuote;
import com.connect.quant.model.ProductQuoteExample;
import org.springframework.stereotype.Repository;

@Repository
public interface ProductQuoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	long countByExample(ProductQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int deleteByExample(ProductQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int insert(ProductQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int insertSelective(ProductQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	List<ProductQuote> selectByExample(ProductQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	ProductQuote selectByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ProductQuote record, @Param("example") ProductQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByExample(@Param("record") ProductQuote record, @Param("example") ProductQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByPrimaryKeySelective(ProductQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByPrimaryKey(ProductQuote record);
}