package com.connect.quant.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.connect.quant.model.StockQuote;
import com.connect.quant.model.StockQuoteExample;

public interface StockQuoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	long countByExample(StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int deleteByExample(StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int insert(StockQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int insertSelective(StockQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	List<StockQuote> selectByExample(StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	StockQuote selectByPrimaryKey(Integer sno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StockQuote record, @Param("example") StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByExample(@Param("record") StockQuote record, @Param("example") StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByPrimaryKeySelective(StockQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Tue Aug 07 14:58:26 CST 2018
	 */
	int updateByPrimaryKey(StockQuote record);
}