package com.connect.quant.dao.mapper;

import com.connect.quant.model.StockQuote;
import com.connect.quant.model.StockQuoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockQuoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	long countByExample(StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int deleteByExample(StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int insert(StockQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int insertSelective(StockQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	List<StockQuote> selectByExample(StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	StockQuote selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StockQuote record, @Param("example") StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByExample(@Param("record") StockQuote record, @Param("example") StockQuoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByPrimaryKeySelective(StockQuote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table STOCK_QUOTE
	 * @mbg.generated  Fri Aug 03 13:21:02 CST 2018
	 */
	int updateByPrimaryKey(StockQuote record);
}